name: "music-mongo"
services: 
  mongoimport:
    image: bitnami/mongodb:latest
    container_name: mongo-import
    volumes:
      - ./database/albums.json:/database/albums.json
      - ./database/artists.json:/database/artists.json
      - ./database/songs.json:/database/songs.json
      - ./database/users.json:/database/users.json
    command: > 
      sh -c "
      mongoimport --host mongodb --db music --collection albums --file /database/albums.json &&
      mongoimport --host mongodb --db music --collection artists --file /database/artists.json &&
      mongoimport --host mongodb --db music --collection songs --file /database/songs.json &&
      mongoimport --host mongodb --db music --collection users --file /database/users.json
      "

  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb-test
    ports:
      - 27017:27017
    depends_on:
    - mongoimport
    restart: always