@id = 66fbccdbd11e93e7d7f7630c
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2ZmJjYjhiYmZmMTNlYmM0MDc4MDA5ZiIsIm5hbWUiOiJKYXZpZXIiLCJzdXJuYW1lIjoiQ2VsYWRhIiwiZW1haWwiOiJjZWxhZGFAdGVzdC5jb20iLCJyb2xlIjoicm9sZV91c2VyIiwiaW1hZ2UiOiJkZWZhdWx0LnBuZyIsImlhdCI6MTcyNzc3NzgxNCwiZXhwIjoiMjAyNC0xMC0zMVQxMToxNjo1NC45ODFaIn0.4c2DTzaAo3LqYbFhem2QeyrWAEq0xiA6hr4qhLXk1y8

POST http://localhost:3911/api/album/profile/{{id}}/upload
Content-Type: multipart/form-data; boundary=AvatarBoundry
Authorization: Bearer {{token}}

--AvatarBoundry
Content-Disposition: form-data; name="image"; filename="album.jpg"
Content-Type: image/jpeg

< ../../images/all-time-low-album.jpeg
--AvatarBoundry--